# Generated by Django 2.1.1 on 2018-11-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_department_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('created_at', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('userinfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.Userinfo')),
            ],
        ),
    ]
