# Generated by Django 2.1.1 on 2018-11-13 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateField(auto_now_add=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='account',
            name='userinfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.Userinfo'),
        ),
    ]
