# Generated by Django 2.1.1 on 2018-11-14 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20181114_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='mobiel',
            new_name='mobile',
        ),
        migrations.AlterField(
            model_name='account',
            name='userinfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.Userinfo'),
        ),
    ]
