# Generated by Django 2.0.9 on 2018-11-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20181114_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='userinfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.Userinfo'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Province'),
        ),
        migrations.AddField(
            model_name='person',
            name='hometown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth', to='news.City'),
        ),
        migrations.AddField(
            model_name='person',
            name='living',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizen', to='news.City'),
        ),
        migrations.AddField(
            model_name='person',
            name='visitation',
            field=models.ManyToManyField(related_name='visitor', to='news.City'),
        ),
    ]
