# Generated by Django 2.1.2 on 2018-11-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perms',
            name='menus',
        ),
        migrations.RemoveField(
            model_name='remoteuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='role',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='role',
            name='perms',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Menus',
        ),
        migrations.DeleteModel(
            name='Perms',
        ),
        migrations.DeleteModel(
            name='RemoteUser',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
