# Generated by Django 2.1.2 on 2018-11-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_log', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLog',
            new_name='UserLog1',
        ),
    ]
